// Generated by scripts/skyline.mjs — the near skyline's tile and its mast tips.
export const NEAR_TILE = { w: 1680, h: 240 } as const;
export const MASTS: readonly (readonly [number, number])[] = [[300,73.5],[753,86],[1156.5,81]];
